apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-deployment
spec:
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-deployment
        image: emaina98/backend:v1.0.4
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  # namespace: ingress-nginx
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
