apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: emaina98/backend-yolo:v2
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  # namespace: ingress-nginx
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
